### ISSUE TITLE
ReplyError: Manager not defined

### ISSUE THREAD

**Issue by ajeetraina** [am2367/RediTeam#3]
While running ```npm run build``` CLI, I see Error messages popping up.

```
ajeetraina@Ajeets-MacBook-Pro RediTeam % npm run load

> RediTeam@0.0.1 load
> node src/models/populateFakeData.js

Completed Populating Fake Data!
Users index has been created
Nodes Created
[
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [
    ReplyError: Manager not defined
        at parseError (/Users/ajeetraina/projects/RediTeam/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/Users/ajeetraina/projects/RediTeam/node_modules/redis-parser/lib/parser.js:302:14) {
      command: [Object]
    }
  ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ]
]
Unexpected error creating employee profile
[
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [
    ReplyError: Manager not defined
        at parseError (/Users/ajeetraina/projects/RediTeam/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/Users/ajeetraina/projects/RediTeam/node_modules/redis-parser/lib/parser.js:302:14) {
      command: [Object]
    }
  ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ]
]
Unexpected error creating employee profile
Employee Profile Created
[
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ]
]
Unexpected error creating employee profile
[
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ]
]
Unexpected error creating employee profile
Employee Profile Created
[
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ]
]
Unexpected error creating employee profile
[
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ]
]
Unexpected error creating employee profile
[
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ]
]
Unexpected error creating employee profile
Registered
Registered
Registered
Registered
[
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ]
]
Unexpected error creating employee profile
Employee Profile Created
[
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ],
  [ null, [ [Array] ] ]
]
Unexpected error creating req
Req Created
Registered
Registered
Registered
Registered
Registered
Registered
Registered
```

I checked with the redis "monitor" command and it shows :

```
)-[r:Is_Closest_To]->(o)"
1626348175.709525 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MATCH(e:Employee{id:9,name:\"Denny Castaneda\",firstName:\"Denny\",lastName:\"Castaneda\",programmingLanguages:[\"Python\"],associateLevel:1,officeLocation:\"Arlington\",teamName:\"Team B\",manager:\"Ardell Hyer\",isManager:false}) MERGE(t:Team{name:\"Team B\"}) MERGE(e)-[r:Is_Part_Of]->(t)"
1626348175.710659 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MATCH(e:Employee{id:9,name:\"Denny Castaneda\",firstName:\"Denny\",lastName:\"Castaneda\",programmingLanguages:[\"Python\"],associateLevel:1,officeLocation:\"Arlington\",teamName:\"Team B\",manager:\"Ardell Hyer\",isManager:false}) MATCH(t:Team{name:\"Team B\"}) MERGE(manager:Manager{name:\"Ardell Hyer\"}) MERGE(e)-[r:Is_Managed_By]->(manager) MERGE(manager)-[r2:Is_Part_Of]->(t)"
1626348175.712115 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MERGE(e:Employee{id:10,name:\"Linnie Laroque\",firstName:\"Linnie\",lastName:\"Laroque\",programmingLanguages:[\"Javascript\",\"Node.js\"],associateLevel:2,officeLocation:\"New York\",teamName:\"Team A\",manager:\"Adrian Yu\",isManager:false}) MERGE(p:ProgrammingLanguage{name:\"javascript\"}) MERGE(e)-[r:Has_Skill]->(p)"
1626348175.712876 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MERGE(e:Employee{id:10,name:\"Linnie Laroque\",firstName:\"Linnie\",lastName:\"Laroque\",programmingLanguages:[\"Javascript\",\"Node.js\"],associateLevel:2,officeLocation:\"New York\",teamName:\"Team A\",manager:\"Adrian Yu\",isManager:false}) MERGE(p:ProgrammingLanguage{name:\"node.js\"}) MERGE(e)-[r:Has_Skill]->(p)"
1626348175.714084 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MATCH(e:Employee{id:10,name:\"Linnie Laroque\",firstName:\"Linnie\",lastName:\"Laroque\",programmingLanguages:[\"Javascript\",\"Node.js\"],associateLevel:2,officeLocation:\"New York\",teamName:\"Team A\",manager:\"Adrian Yu\",isManager:false}) MATCH(a:AssociateLevel{level:2}) MERGE(e)-[r:Is_Associate_Level]->(a)"
1626348175.716021 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MATCH(e:Employee{id:10,name:\"Linnie Laroque\",firstName:\"Linnie\",lastName:\"Laroque\",programmingLanguages:[\"Javascript\",\"Node.js\"],associateLevel:2,officeLocation:\"New York\",teamName:\"Team A\",manager:\"Adrian Yu\",isManager:false}) MATCH(o:OfficeLocation{name:\"New York\"}) MERGE(e)-[r:Is_Closest_To]->(o)"
1626348175.717512 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MATCH(e:Employee{id:10,name:\"Linnie Laroque\",firstName:\"Linnie\",lastName:\"Laroque\",programmingLanguages:[\"Javascript\",\"Node.js\"],associateLevel:2,officeLocation:\"New York\",teamName:\"Team A\",manager:\"Adrian Yu\",isManager:false}) MERGE(t:Team{name:\"Team A\"}) MERGE(e)-[r:Is_Part_Of]->(t)"
1626348175.718436 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MATCH(e:Employee{id:10,name:\"Linnie Laroque\",firstName:\"Linnie\",lastName:\"Laroque\",programmingLanguages:[\"Javascript\",\"Node.js\"],associateLevel:2,officeLocation:\"New York\",teamName:\"Team A\",manager:\"Adrian Yu\",isManager:false}) MATCH(t:Team{name:\"Team A\"}) MERGE(manager:Manager{name:\"Adrian Yu\"}) MERGE(e)-[r:Is_Managed_By]->(manager) MERGE(manager)-[r2:Is_Part_Of]->(t)"
1626348175.719904 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MERGE(e:Employee{id:11,name:\"John Smith\",firstName:\"John\",lastName:\"Smith\",programmingLanguages:[\"Javascript\",\"Node.js\",\"Python\"],associateLevel:3,officeLocation:\"San Francisco\",teamName:\"Team A\",manager:\"Adrian Yu\",isManager:false}) MERGE(p:ProgrammingLanguage{name:\"javascript\"}) MERGE(e)-[r:Has_Skill]->(p)"
1626348175.721214 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MERGE(e:Employee{id:11,name:\"John Smith\",firstName:\"John\",lastName:\"Smith\",programmingLanguages:[\"Javascript\",\"Node.js\",\"Python\"],associateLevel:3,officeLocation:\"San Francisco\",teamName:\"Team A\",manager:\"Adrian Yu\",isManager:false}) MERGE(p:ProgrammingLanguage{name:\"node.js\"}) MERGE(e)-[r:Has_Skill]->(p)"
1626348175.722241 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MERGE(e:Employee{id:11,name:\"John Smith\",firstName:\"John\",lastName:\"Smith\",programmingLanguages:[\"Javascript\",\"Node.js\",\"Python\"],associateLevel:3,officeLocation:\"San Francisco\",teamName:\"Team A\",manager:\"Adrian Yu\",isManager:false}) MERGE(p:ProgrammingLanguage{name:\"python\"}) MERGE(e)-[r:Has_Skill]->(p)"
1626348175.723848 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MATCH(e:Employee{id:11,name:\"John Smith\",firstName:\"John\",lastName:\"Smith\",programmingLanguages:[\"Javascript\",\"Node.js\",\"Python\"],associateLevel:3,officeLocation:\"San Francisco\",teamName:\"Team A\",manager:\"Adrian Yu\",isManager:false}) MATCH(a:AssociateLevel{level:3}) MERGE(e)-[r:Is_Associate_Level]->(a)"
1626348175.725250 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MATCH(e:Employee{id:11,name:\"John Smith\",firstName:\"John\",lastName:\"Smith\",programmingLanguages:[\"Javascript\",\"Node.js\",\"Python\"],associateLevel:3,officeLocation:\"San Francisco\",teamName:\"Team A\",manager:\"Adrian Yu\",isManager:false}) MATCH(o:OfficeLocation{name:\"San Francisco\"}) MERGE(e)-[r:Is_Closest_To]->(o)"
1626348175.726309 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MATCH(e:Employee{id:11,name:\"John Smith\",firstName:\"John\",lastName:\"Smith\",programmingLanguages:[\"Javascript\",\"Node.js\",\"Python\"],associateLevel:3,officeLocation:\"San Francisco\",teamName:\"Team A\",manager:\"Adrian Yu\",isManager:false}) MERGE(t:Team{name:\"Team A\"}) MERGE(e)-[r:Is_Part_Of]->(t)"
1626348175.727410 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MATCH(e:Employee{id:11,name:\"John Smith\",firstName:\"John\",lastName:\"Smith\",programmingLanguages:[\"Javascript\",\"Node.js\",\"Python\"],associateLevel:3,officeLocation:\"San Francisco\",teamName:\"Team A\",manager:\"Adrian Yu\",isManager:false}) MATCH(t:Team{name:\"Team A\"}) MERGE(manager:Manager{name:\"Adrian Yu\"}) MERGE(e)-[r:Is_Managed_By]->(manager) MERGE(manager)-[r2:Is_Part_Of]->(t)"
1626348175.729108 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MERGE(req:Req{name:\"Software Engineer 2\",managerId:1,teamName:\"Team A\",manager:\"Adrian Yu\",associateLevel:2,programmingLanguages:[\"Javascript\",\"Node.js\"],officeLocation:\"New York\",description:\"Looking for a strong Javascript engineer to build and maintain our awesome full stack apps!\"}) MERGE(p:ProgrammingLanguage{name:\"javascript\"}) MERGE(req)-[r:Requires_Skill]->(p)"
1626348175.730255 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MERGE(req:Req{name:\"Software Engineer 2\",managerId:1,teamName:\"Team A\",manager:\"Adrian Yu\",associateLevel:2,programmingLanguages:[\"Javascript\",\"Node.js\"],officeLocation:\"New York\",description:\"Looking for a strong Javascript engineer to build and maintain our awesome full stack apps!\"}) MERGE(p:ProgrammingLanguage{name:\"node.js\"}) MERGE(req)-[r:Requires_Skill]->(p)"
1626348175.731643 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MATCH(req:Req{name:\"Software Engineer 2\",managerId:1,teamName:\"Team A\",manager:\"Adrian Yu\",associateLevel:2,programmingLanguages:[\"Javascript\",\"Node.js\"],officeLocation:\"New York\",description:\"Looking for a strong Javascript engineer to build and maintain our awesome full stack apps!\"}) MATCH(a:AssociateLevel{level:2}) MERGE(req)-[r:Requires_Associate_Level]->(a)"
1626348175.732792 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MATCH(req:Req{name:\"Software Engineer 2\",managerId:1,teamName:\"Team A\",manager:\"Adrian Yu\",associateLevel:2,programmingLanguages:[\"Javascript\",\"Node.js\"],officeLocation:\"New York\",description:\"Looking for a strong Javascript engineer to build and maintain our awesome full stack apps!\"}) MATCH(o:OfficeLocation{name:\"New York\"}) MERGE(req)-[r:Requires_Office_Location]->(o)"
1626348175.734384 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MATCH(req:Req{name:\"Software Engineer 2\",managerId:1,teamName:\"Team A\",manager:\"Adrian Yu\",associateLevel:2,programmingLanguages:[\"Javascript\",\"Node.js\"],officeLocation:\"New York\",description:\"Looking for a strong Javascript engineer to build and maintain our awesome full stack apps!\"}) MATCH(e:Manager{id:1})--(t:Team) MERGE(req)-[r:Hiring_For]->(t) SET req.teamName=t.name SET req.manager=e.name"
1626348175.735938 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MATCH(req:Req{name:\"Software Engineer 2\",managerId:1,teamName:\"Team A\",manager:\"Adrian Yu\",associateLevel:2,programmingLanguages:[\"Javascript\",\"Node.js\"],officeLocation:\"New York\",description:\"Looking for a strong Javascript engineer to build and maintain our awesome full stack apps!\"}) MATCH(e:Manager{id:1}) MERGE(req)-[r:Hiring_Manager]->(e)"
1626348175.737121 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MERGE(req:Req{name:\"Software Engineer 3\",managerId:3,teamName:\"Team C\",manager:\"Ranee Dubreuil\",associateLevel:3,programmingLanguages:[\"Javascript\",\"Node.js\",\"Python\"],officeLocation:\"San Francisco\",description:\"Looking for a very capable engineer with lots of Javascript and Python experience to help lead the buildout out of some of our new systems.\"}) MERGE(p:ProgrammingLanguage{name:\"javascript\"}) MERGE(req)-[r:Requires_Skill]->(p)"
1626348175.738871 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MERGE(req:Req{name:\"Software Engineer 3\",managerId:3,teamName:\"Team C\",manager:\"Ranee Dubreuil\",associateLevel:3,programmingLanguages:[\"Javascript\",\"Node.js\",\"Python\"],officeLocation:\"San Francisco\",description:\"Looking for a very capable engineer with lots of Javascript and Python experience to help lead the buildout out of some of our new systems.\"}) MERGE(p:ProgrammingLanguage{name:\"node.js\"}) MERGE(req)-[r:Requires_Skill]->(p)"
1626348175.740644 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MERGE(req:Req{name:\"Software Engineer 3\",managerId:3,teamName:\"Team C\",manager:\"Ranee Dubreuil\",associateLevel:3,programmingLanguages:[\"Javascript\",\"Node.js\",\"Python\"],officeLocation:\"San Francisco\",description:\"Looking for a very capable engineer with lots of Javascript and Python experience to help lead the buildout out of some of our new systems.\"}) MERGE(p:ProgrammingLanguage{name:\"python\"}) MERGE(req)-[r:Requires_Skill]->(p)"
1626348175.742724 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MATCH(req:Req{name:\"Software Engineer 3\",managerId:3,teamName:\"Team C\",manager:\"Ranee Dubreuil\",associateLevel:3,programmingLanguages:[\"Javascript\",\"Node.js\",\"Python\"],officeLocation:\"San Francisco\",description:\"Looking for a very capable engineer with lots of Javascript and Python experience to help lead the buildout out of some of our new systems.\"}) MATCH(a:AssociateLevel{level:3}) MERGE(req)-[r:Requires_Associate_Level]->(a)"
1626348175.744474 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MATCH(req:Req{name:\"Software Engineer 3\",managerId:3,teamName:\"Team C\",manager:\"Ranee Dubreuil\",associateLevel:3,programmingLanguages:[\"Javascript\",\"Node.js\",\"Python\"],officeLocation:\"San Francisco\",description:\"Looking for a very capable engineer with lots of Javascript and Python experience to help lead the buildout out of some of our new systems.\"}) MATCH(o:OfficeLocation{name:\"San Francisco\"}) MERGE(req)-[r:Requires_Office_Location]->(o)"
1626348175.746218 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MATCH(req:Req{name:\"Software Engineer 3\",managerId:3,teamName:\"Team C\",manager:\"Ranee Dubreuil\",associateLevel:3,programmingLanguages:[\"Javascript\",\"Node.js\",\"Python\"],officeLocation:\"San Francisco\",description:\"Looking for a very capable engineer with lots of Javascript and Python experience to help lead the buildout out of some of our new systems.\"}) MATCH(e:Manager{id:3})--(t:Team) MERGE(req)-[r:Hiring_For]->(t) SET req.teamName=t.name SET req.manager=e.name"
1626348175.747885 [0 172.17.0.1:57356] "GRAPH.QUERY" "Employee" "MATCH(req:Req{name:\"Software Engineer 3\",managerId:3,teamName:\"Team C\",manager:\"Ranee Dubreuil\",associateLevel:3,programmingLanguages:[\"Javascript\",\"Node.js\",\"Python\"],officeLocation:\"San Francisco\",description:\"Looking for a very capable engineer with lots of Javascript and Python experience to help lead the buildout out of some of our new systems.\"}) MATCH(e:Manager{id:3}) MERGE(req)-[r:Hiring_Manager]->(e)"
1626348175.749305 [0 172.17.0.1:57356] "hset" "users:3" "id" "3" "email" "ranee.dubreuil@test.com" "password" "$2b$10$uBF75qqB8hj4G7W6E0BnmudJEOf9vl6liYe.kfdULcJDhcppMNmYe"
1626348175.749598 [0 172.17.0.1:57356] "hset" "users:1" "id" "1" "email" "adrian.yu@test.com" "password" "$2b$10$XRvxZIB2BChCfe4kIsNS4.ENoiJ/EiimdCX61MQMgAPgl/9JlM1QG"
1626348175.749650 [0 172.17.0.1:57356] "hset" "users:6" "id" "6" "email" "sol.heckel@test.com" "password" "$2b$10$xXB/Dc02PewuxfWmddSYdu2HHhraU6EV.BNq1REOLbeA8liExKubO"
1626348175.749709 [0 172.17.0.1:57356] "hset" "users:5" "id" "5" "email" "maximo.radford@test.com" "password" "$2b$10$cxocPfrT7IADFWOf7oxiru9p0Oqm5h4e79M9ry/s4RKgUrJiSppRu"
1626348175.782893 [0 172.17.0.1:57356] "hset" "users:8" "id" "8" "email" "chi.romanik@test.com" "password" "$2b$10$ZxtIIJMiYtcBlp91OOf7QesWpVOmS8i6cQ3oz1K3HTigkyViAvSCm"
1626348175.783218 [0 172.17.0.1:57356] "hset" "users:7" "id" "7" "email" "giuseppina.gobin@test.com" "password" "$2b$10$joRlQ2WrLuqL2rdM7Y9Sb.58vRDaYdfXCXV1sEgVO7I5.eXC2Tyom"
1626348175.783280 [0 172.17.0.1:57356] "hset" "users:4" "id" "4" "email" "camille.crosbie@test.com" "password" "$2b$10$TG7KcPg7uNYFy9emV2KAMeX/X6sfmtUPAakR7SU.UsGgOboTt17D6"
1626348175.783325 [0 172.17.0.1:57356] "hset" "users:9" "id" "9" "email" "denny.castaneda@test.com" "password" "$2b$10$GR1sArXQ29M5Nhl7.mvcAuiklxfA21h36xqivk8Szwtj2xztHYN0y"
1626348175.848782 [0 172.17.0.1:57356] "hset" "users:10" "id" "10" "email" "linnie.laroque@test.com" "password" "$2b$10$K0Tynho9Kv27jGs4pwjffeiPp74nLflpuVVMYpD3sSxPpQw74J2h."
1626348175.849084 [0 172.17.0.1:57356] "hset" "users:2" "id" "2" "email" "ardell.hyer@test.com" "password" "$2b$10$wvzvBwgGnVOOBfAZhQfDsucmN06oPdmFic.3pe6PxQ/fQaz.erEWG"
1626348175.849152 [0 172.17.0.1:57356] "hset" "users:11" "id" "11" "email" "john.smith@test.com" "password" "$2b$10$YZ8MNqfggDV9Ar1mFz2OPOFGrLYOboDnV7gy5M.CwtHA9gZure22K"

```

**Comment by am2367** [comment]
Hey Ajeet, there are some expected errors during the data load which I mentioned to ignore in the readme. I haven't fixed those errors yet but they shouldn't impact the load itself. Try logging into the application with some of the users to confirm they were loaded correctly along with the team managers.
